apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: metacoding
type: Opaque
stringData:
  MYSQL_ROOT_PASSWORD: root1234
  MYSQL_DATABASE: metadb
  MYSQL_USER: metacoding 
  MYSQL_PASSWORD: metacoding1234