apiVersion: v1
kind: Service
metadata:
  name: user-service
  namespace: metacoding
spec:
  type: ClusterIP  # 내부 통신만 허용(기본값)
  selector:
    app: user
  ports:
    - port: 8083
      targetPort: 8083